### ISSUE TITLE
Not working with tmux commands on split

### ISSUE THREAD

**Issue by carlitux** [wbyoung/avn#16]
When I start a command on tmux like

tmux split-window -v -p 20 -t session "grunt"

It is not switching to .node-version

**Comment by wbyoung** [comment]
@carlitux I'd be happy to accept a pull request for this, but it won't be a priority since using tmux is a pretty custom configuration & this project won't be able to reasonably ensure compatibility with every possible configuration.

Having said that, it could point to an underlying issue in the architecture.

The shell components are based off of how [RVM](https://rvm.io/) integrates with the shell. If you're a ruby user & use RVM, does that work with the `tmux` command?

Also, the triggers for `avn` running are when you `cd` or when your `~/.bash_profile` is executed. If neither of these are happening when you expect a switch to occur (because of how `tmux` works), then nothing will happen.

**Comment by carlitux** [comment]
@wbyoung I was reading doc and looks like without the quotation on command works fine... Thank you very much.

**Comment by wbyoung** [comment]
@carlitux ok, glad to hear you got it working.
